{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-credentials
type: Opaque
data:
  accessKey: {{ .Values.minio.accessKey | b64enc }}
  secretKey: {{ .Values.minio.secretKey | b64enc }}
{{- end }}