{{- if .Values.postgres.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  serviceName: {{ .Release.Name }}-postgres-service
  replicas: {{ .Values.postgres.replicas | default 1 }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.postgres.database | default "5432" }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | default "postgres" }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | default "postgres" }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: {{ .Values.postgres.passwordKey }}
            - name: _PG_CREATE_DATABASES
              value: "{{ .Values.postgres.database | default "koku" }}|{{ .Values.postgres.user | default "koku" }},unleash|{{ .Values.postgres.user | default "koku" }}"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user | default "koku" }}
                - -d
                - {{ .Values.postgres.database | default "koku" }}
            initialDelaySeconds: 5
            periodSeconds: 2
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.postgres.storage | default "10Gi" }}
{{- end }}