image:
  repository: ghcr.io/ennva/koku
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8000

env:
  DATABASE_SERVICE_NAME: POSTGRES_SQL
  DATABASE_ENGINE: postgresql
  DATABASE_NAME: koku
  DATABASE_USER: koku
  DATABASE_PASSWORD: koku
  DATABASE_HOST: postgresql
  DATABASE_PORT: "5432"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: koku.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

serviceAccount:
  create: true
  name: ""