{{- if .Values.kokuBaseDev.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-test-customer
spec:
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: create-test-customer
          image: {{ .Values.kokuBaseDev.image }}
          imagePullPolicy: {{ .Values.kokuBaseDev.imagePullPolicy | default "IfNotPresent" }}
          workingDir: /opt/koku
          command:
            - /bin/sh
            - -c
            - |
              echo "⏳ Checking PostgreSQL availability at koku-postgres-service:5432..."

              python3 -c "
              import socket, time, sys

              host = 'koku-postgres-service'
              port = 5432

              for i in range(30):
                  try:
                      with socket.create_connection((host, port), timeout=2):
                          print('✅ PostgreSQL is available.')
                          sys.exit(0)
                  except Exception:
                      print(f'Waiting ({i + 1})...')
                      time.sleep(2)

              print('❌ Timeout: PostgreSQL not reachable.')
              sys.exit(1)
              "

              echo "📦 List content of current directory..."
              pwd
              ls -R dev/scripts/

              echo "📦 Ensuring pyyaml is available..."
              /opt/koku/.venv/bin/python -m pip show PyYAML

              echo "🚀 Running create_test_customer.py..."
              /opt/koku/.venv/bin/python /opt/koku/dev/scripts/create_test_customer.py || echo "⚠️ Script failed!"
          #volumeMounts:
          #  - name: scripts
          #    mountPath: /opt/koku/scripts
      #volumes:
      #  - name: scripts
      #    configMap:
      #      name: create-test-customer
      #      defaultMode: 0777
{{- end }}

