{{- if .Values.unleash.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-unleash-config
data:
  flags.json: |-
    {{ .Values.unleash.flags | default "{}" | toYaml | indent 4 }}
{{- end }}