{{- if .Values.pgadmin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - port: {{ .Values.pgadmin.port }}
      targetPort: {{ .Values.pgadmin.containerPort }}
{{- end }}