{{- if .Values.kokuServer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-koku-server
  labels:
    app.kubernetes.io/name: koku-server
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1 # You might want to make this configurable in values.yaml
  selector:
    matchLabels:
      app.kubernetes.io/name: koku-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: koku-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      containers:
        - name: koku-server
          image: {{ .Values.kokuServer.image }}
          #workingDir: {{ .Values.kokuServer.workingDir }}
          #entrypoint: {{ .Values.kokuServer.entrypoint }}
          ports:
            {{- range .Values.kokuServer.ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.kokuServer.environment }}
            - name: {{ $key }}
              value: {{ quote $value }}
            {{- end }}
          volumeMounts:
            {{- range .Values.kokuServer.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
            {{- end }}
      volumes:
        {{- range .Values.kokuServer.volumes }}
        - name: {{ .name }}
          {{- if .secret }}
          secret:
            secretName: {{ .secret.secretName }}
          {{- else }}
          emptyDir: {} # You'll need to configure the actual volume source
          {{- end }}
        {{- end }}
{{- end }}        